name: Terraform CI-CD

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  TF_WORKING_DIR: environment/dev

jobs:

  # ==================================================
  # SECURITY AGENT
  # ==================================================
  security:
    name: Security Agent
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout source code
      - name: Checkout Code
        uses: actions/checkout@v4


      # 2. Gitleaks - Secret Detection
      - name: Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2


      # 3. Setup TFLint
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4


      # 4. Run TFLint
      - name: TFLint Scan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          tflint --init
          tflint


      # 5. Checkov - Terraform Security Scan
      - name: Checkov Scan
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ${{ env.TF_WORKING_DIR }


  # ==================================================
  # TERRAFORM
  # ==================================================
  terraform:
    name: Terraform
    needs: security
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout source code
      - name: Checkout Code
        uses: actions/checkout@v4


      # 2. Azure Login using OIDC
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: "24623e13-3c30-4d95-bd03-1320e53394d9"
          tenant-id: "e8e1bab7-6578-4fda-8bc7-b6a7746c93f7"
          subscription-id: "87517155-e28d-4d9b-b1ee-f212445262ff"


      # 3. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3


      # 4. Terraform Format Check
      - name: Terraform Format
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform fmt -check -recursive


      # 5. Terraform Init
      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init


      # 6. Terraform Validate
      - name: Terraform Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform validate


      # 7. Terraform Plan
      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -out=tfplan


      # 8. Terraform Apply
      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -auto-approve tfplan